initial_company_research:
  description: >
    Research {company} using search the internet tool and
    extract information from it's website, website_url: {website} using the read website tool.
  expected_output: >
    Create a bullet point list of company information.

research_industry_needs:
  description: >
    Research on {industry} industry and {category} category using search the internet tool.
    Look for common industry technological challenges and pain points.
  expected_output: >
    Bullet point list of common industry technological challenges and pain points.

sales_pitch:
  description: >
    Use the report on {company} and challenges on {industry} industry,
    then identify how {sender_company} can address potential needs using summary: {sender_summary}. 
    Look for unique angles or shared points of interest that can be used to create a strong connection.
  expected_output: >
    A list of personalized talking points and angles to use in the email,
    connecting {company}'s business context, industry challenges, and goals
    with the benefits that {sender_company} can provide. Include relevant details
    from their social media presence and website to demonstrate thorough research.

write_sales_email:
  description: >
    Craft a concise (300–500 words), personalized HTML email to {company} based on the research and personalization insights. 
    Draw from {industry}, {category}, and recent business activities to show a deep understanding of their context. 
    Highlight how {sender_company}’s offerings ({sender_summary}) align with their needs.

    The middle section of the email (email_body) must:
    - Use only <tr>, <td>, <p>, <li>, <ul>, <ol>, and <strong> tags (plus minimal inline styling if needed)
    - Reference specific details from their online presence ({website}, social media) to prove thorough research
    - Present 2–3 key value propositions or benefits in short paragraphs or list items
    - Use clear, simple sentences (no jargon or overly technical terms)
    - Avoid placeholders or leftover template variables (e.g., "{{placeholder}}")

    The final HTML email already contains:
    - A greeting line that addresses the company
    - A closing section with a Calendly link and contact details

    Your job is to supply only the HTML body portion that goes between the greeting and the closing.

  expected_output: >
    An EmailOutput object containing a list of PersonalizedEmail objects, each with:
    1. The recipient's email address in the "to" field
    2. A subject line (max 60 characters) referencing the research findings and value proposition
    3. A middle portion of HTML (email_body) that is 300–500 words long, demonstrates understanding of the prospect, 
       uses only the allowed HTML tags, and references their digital presence. It must feature a clear call to action, 
       incorporate 2–3 key benefits, and use the exact sender information provided:
         - Sender Name: {sender_full_name}
         - Title: {sender_title}
         - Company: {sender_company}
         - Phone: {sender_phone}
         - Email: {sender_email}
         - Website: {sender_website}
         - Recipient Email: {email}
       Do not include any unused placeholders or variables in this final HTML content.

