initial_company_research:
  description: >
    Research {company} using search the internet tool and
    extract information from it's website, website_url: {website} using the read website tool.
  expected_output: >
    Create a bullet point list of company information.

research_industry_needs:
  description: >
    Research on {industry} industry and {category} category using search the internet tool.
    Look for common industry technological challenges and pain points.
  expected_output: >
    Bullet point list of common industry technological challenges and pain points.

sales_pitch:
  description: >
    Use the report on {company} and challenges on {industry} industry,
    then identify how {sender_company} can address potential needs using summary: {sender_summary}. 
    Look for unique angles or shared points of interest that can be used to create a strong connection.
  expected_output: >
    A list of personalized talking points and angles to use in the email,
    connecting {company}'s business context, industry challenges, and goals
    with the benefits that {sender_company} can provide. Include relevant details
    from their social media presence and website to demonstrate thorough research.

write_sales_email:
  description: >
    Craft a concise, personalized email (300-500 words) to {company} based on the research and personalization insights.
    Use the research findings about their industry ({industry}), category ({category}),
    and recent activities to create an email that demonstrates deep understanding. Incorporate elements
    from {sender_company}'s value proposition ({sender_summary}) to show clear alignment and value.
    The email should reference specific details from their digital presence ({website}, social media)
    to prove thorough research while maintaining a professional yet conversational tone.
    IMPORTANT: Use the exact sender information provided:
    - Sender Name: {sender_full_name}
    - Title: {sender_title}
    - Company: {sender_company}
    - Phone: {sender_phone}
    - Email: {sender_email}
    - Website: {sender_website}
    - Recipient Email: {email}
  expected_output: >
    An EmailOutput object containing a list of PersonalizedEmail objects, each with:
    1. The recipient's email address in the 'to' field
    2. A compelling subject line that demonstrates research insights and value proposition (max 60 chars)
    3. A concise email body (300-500 words) that:
       - Shows deep understanding of the prospect's business and industry context
       - References specific details from their online presence and recent activities 
       - Clearly articulates 2-3 key value propositions and benefits
       - Includes a clear call-to-action for next steps
       - Uses the exact sender contact information provided
       - Contains no placeholder text or template variables

